# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    twist_controller:
      type: picknik_twist_controller/PicknikTwistController


    robotiq_gripper_controller:
      type: position_controllers/GripperActionController


    fault_controller:
      type: picknik_reset_fault_controller/PicknikResetFaultController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
twist_controller:
  ros__parameters:
    joints:
      - tcp
robotiq_gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
fault_controller:
  ros__parameters:
    joints:
      []