controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    twist_controller:
      type: picknik_twist_controller/PicknikTwistController

    robotiq_gripper_controller:
      type: position_controllers/GripperActionController

    fault_controller:
      type: picknik_reset_fault_controller/PicknikResetFaultController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

velocity_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    gains:
      joint_1: { p: 0.50, d: 10.0, i: 1.0 }
      joint_2: { p: 0.50, d: 10.0, i: 1.0 }
      joint_3: { p: 0.50, d: 10.0, i: 1.0 }
      joint_4: { p: 0.50, d: 10.0, i: 1.0 }
      joint_5: { p: 0.50, d: 10.0, i: 1.0 }
      joint_6: { p: 0.50, d: 10.0, i: 1.0 }
      joint_7: { p: 0.50, d: 10.0, i: 1.0 }
    allow_partial_joints_goal: true
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

twist_controller:
  ros__parameters:
    joint: tcp
    interface_names:
      - twist.linear.x
      - twist.linear.y
      - twist.linear.z
      - twist.angular.x
      - twist.angular.y
      - twist.angular.z

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: robotiq_85_left_knuckle_joint
    allow_stalling: true
